[package]
name                    = "pion-source"
version                 = { workspace = true }
edition                 = { workspace = true }
rust-version            = { workspace = true }

[dependencies]
salsa                   = { workspace = true }
