[package]
name                    = "pion-common"
version                 = { workspace = true }
edition                 = { workspace = true }
rust-version            = { workspace = true }

[dependencies]
bumpalo                 = { workspace = true }
