[package]
name = "pion-surface"
version = "0.1.0"
edition = "2021"

[dependencies]
pion-source = { version = "0.1.0", path = "../pion-source" }

lalrpop-util = "0.19.8"
logos = "0.12.1"
scoped-arena = "0.4.1"
lexical = { version = "6.1.1", features = ["power-of-two", "format"] }

[build-dependencies]
lalrpop = { git = "https://github.com/kmeakin/lalrpop", branch = "raw-identifiers" }
