[package]
name = "pion-surface"
version = "0.1.0"
edition = "2021"

[dependencies]
pion-source = { version = "0.1.0", path = "../pion-source" }

lalrpop-util = "0.19.8"
lexical = { version = "6.1.1", features = ["power-of-two", "format"] }
logos = "0.12.1"
scoped-arena = "0.4.1"
ustr = "0.9.0"
pretty = "0.11.3"
codespan-reporting = "0.11.1"

[build-dependencies]
lalrpop = { git = "https://github.com/kmeakin/lalrpop", branch = "raw-identifiers" }
